# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

terms, even_terms = [1, 2], [2]

while terms.last < 4000000
  new_term   =  terms[-1] + terms[-2]
  even_terms << new_term if new_term.even?
  terms      << new_term
end

puts even_terms.inject(:+)
